// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ypUV9NI21ZznBK42MxSkHmn1ejYfRpo',
    appId: '1:751385478416:web:7761be4a2371598feed195',
    messagingSenderId: '751385478416',
    projectId: 'userauth-dbf91',
    authDomain: 'userauth-dbf91.firebaseapp.com',
    storageBucket: 'userauth-dbf91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHpHls0Guf5Ndy2aNF_angrvenPWsCqFU',
    appId: '1:751385478416:android:3be5bc4c45965324eed195',
    messagingSenderId: '751385478416',
    projectId: 'userauth-dbf91',
    storageBucket: 'userauth-dbf91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUpr6jhUf8st2EOkQviXJPaXjvmxs89QY',
    appId: '1:751385478416:ios:9630cf2b58f0a59deed195',
    messagingSenderId: '751385478416',
    projectId: 'userauth-dbf91',
    storageBucket: 'userauth-dbf91.appspot.com',
    iosBundleId: 'com.example.uniIbadanNavigator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUpr6jhUf8st2EOkQviXJPaXjvmxs89QY',
    appId: '1:751385478416:ios:f1eeebca6113051eeed195',
    messagingSenderId: '751385478416',
    projectId: 'userauth-dbf91',
    storageBucket: 'userauth-dbf91.appspot.com',
    iosBundleId: 'com.example.uniIbadanNavigator.RunnerTests',
  );
}
